# Generated by Django 6.0.1 on 2026-01-21 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'ingredient categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('categories', models.ManyToManyField(help_text='Categories this ingredient belongs to', related_name='ingredients', to='ingredients.ingredientcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientCategoryAncestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveIntegerField(help_text='Distance from category to ancestor (0 = self, 1 = parent, etc.)')),
                ('ancestor', models.ForeignKey(help_text='An ancestor of the category (including self at depth 0)', on_delete=django.db.models.deletion.CASCADE, related_name='descendant_links', to='ingredients.ingredientcategory')),
                ('category', models.ForeignKey(help_text='The category whose ancestors are being stored', on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_links', to='ingredients.ingredientcategory')),
            ],
            options={
                'verbose_name': 'category ancestor',
                'verbose_name_plural': 'category ancestors',
                'unique_together': {('category', 'ancestor')},
            },
        ),
    ]
