# Generated by Django 6.0.1 on 2026-01-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='needs_categorization',
            field=models.BooleanField(default=False, help_text='Flag for ingredients needing category assignment'),
        ),
    ]
