# Generated by Django 6.0.1 on 2026-01-21 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('source', models.CharField(blank=True, help_text="Source of the recipe (e.g., 'Death & Co', 'PDT')", max_length=200)),
                ('page', models.PositiveIntegerField(blank=True, help_text='Page number in source book', null=True)),
                ('method', models.TextField(blank=True, help_text='Preparation instructions')),
                ('garnish', models.TextField(blank=True, help_text='Garnish description')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the recipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, help_text="Amount (e.g., '2', '3/4', '2-3')", max_length=50)),
                ('unit', models.CharField(blank=True, help_text="Unit of measurement (e.g., 'oz', 'dash', 'barspoon')", max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of ingredient in recipe')),
                ('optional', models.BooleanField(default=False, help_text='Is this ingredient optional?')),
                ('notes', models.CharField(blank=True, help_text='Notes about this ingredient in the recipe', max_length=200)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_uses', to='ingredients.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'recipe ingredient',
                'verbose_name_plural': 'recipe ingredients',
                'ordering': ['order'],
            },
        ),
    ]
