# Generated by Django 6.0.1 on 2026-01-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Numeric amount (e.g., 1.5 for '1 1/2')", max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='notes',
            field=models.CharField(blank=True, help_text="Notes (e.g., '2-3 dashes' when amount is minimum)", max_length=200),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('oz', 'ounce'), ('ml', 'milliliter'), ('cl', 'centiliter'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('barspoon', 'barspoon'), ('dash', 'dash'), ('drop', 'drop'), ('rinse', 'rinse'), ('float', 'float'), ('top', 'top'), ('splash', 'splash'), ('whole', 'whole'), ('piece', 'piece'), ('slice', 'slice'), ('wedge', 'wedge'), ('sprig', 'sprig'), ('leaf', 'leaf')], help_text='Unit of measurement', max_length=20),
        ),
    ]
