# Generated by Django 6.0.1 on 2026-01-31 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image', models.ImageField(help_text='Image of recipe page to parse', upload_to='recipe_imports/')),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('parsed', 'Parsed - Awaiting Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('error', 'Parse Error')], default='pending', max_length=20)),
                ('parse_error', models.TextField(blank=True, help_text='Error message if parsing failed')),
                ('parsed_data', models.JSONField(blank=True, help_text='Parsed recipe data from AI', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When parsing completed', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When import was approved', null=True)),
                ('recipe', models.ForeignKey(blank=True, help_text='Recipe created from this import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'recipe import',
                'verbose_name_plural': 'recipe imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
