# Generated by Django 6.0.1 on 2026-02-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimport',
            name='raw_ocr_text',
            field=models.TextField(blank=True, help_text='Raw OCR text extracted from image (for debugging)'),
        ),
    ]
