# Generated by Django 6.0.1 on 2026-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_seed_taste_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimport',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipeimport',
            name='recipes',
            field=models.ManyToManyField(blank=True, help_text='Recipes created or updated from this import', related_name='imports', to='recipes.recipe'),
        ),
    ]
